import * as v from 'valibot'

const envSchema = v.object({
	EXPO_PUBLIC_PORTAL_URL: v.string(),
	EXPO_PUBLIC_PORTAL_AUTH_URL: v.string(),
	EXPO_PUBLIC_ADMIN_URL: v.string(),
	EXPO_PUBLIC_ADMIN_AUTH_TOKEN: v.string(),
	EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_ID: v.string(),
	EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_SECRET: v.string(),
	EXPO_PUBLIC_USER_ATTR_SERVICE_TOKEN_CLIENT_SECRET: v.string(),
})

export type EnvSchema = v.InferInput<typeof envSchema>

export const env = {
	EXPO_PUBLIC_PORTAL_URL: process.env.EXPO_PUBLIC_PORTAL_URL,
	EXPO_PUBLIC_PORTAL_AUTH_URL: process.env.EXPO_PUBLIC_PORTAL_AUTH_URL,
	EXPO_PUBLIC_ADMIN_URL: process.env.EXPO_PUBLIC_ADMIN_URL,
	EXPO_PUBLIC_ADMIN_AUTH_TOKEN: process.env.EXPO_PUBLIC_ADMIN_AUTH_TOKEN,
	EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_ID: process.env.EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_ID,
	EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_SECRET: process.env.EXPO_PUBLIC_SERVICE_TOKEN_CLIENT_SECRET,
	EXPO_PUBLIC_USER_ATTR_SERVICE_TOKEN_CLIENT_SECRET: process.env.EXPO_PUBLIC_USER_ATTR_SERVICE_TOKEN_CLIENT_SECRET,
}
